name: goes2go
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - git
  - toml
  - jupyter
  - jupyterlab
  - netcdf4
  - h5netcdf
  - xarray
  - numpy
  - matplotlib
  - pandas
  - cartopy
  - s3fs
  - metpy

  # Formatter (I prefer Black at the moment)
  - black
  - autopep8

  - pip:
      # Install from PyPi
      #- goes2go
      # * or install most recent version on GitHub
      - git+https://github.com/blaylockbk/goes2go.git

      # Borrow some tools from my garage
      - git+https://github.com/blaylockbk/Carpenter_Workshop.git
