name: goes2go
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - git
  - jupyter
  - jupyterlab
  - netcdf4
  - xarray
  - numpy
  - matplotlib
  - pandas
  - cartopy
  - s3fs
  - pip:
    - git+https://github.com/blaylockbk/goes2go.git
    - git+https://github.com/blaylockbk/Carpenter_Workshop.git  # "Can I borrow your hammer?"
